version: '3.9'  

services:
  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi

  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80" 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
